config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/dashboard'

  match 'send_message', to: 'pages#send_welcome', via: [:get, :post], as: :send_welcome
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_token
  private
  def set_token
    return cookies[:data] if defined? cookies[:data]

    cookies[:data] ||= 'no hay token'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def dashboard
  end

  def send_welcome
    w = WhatsappManager.new
    @response = w.send_message("welcome_blipol", "34625650792".to_i, "creaDix","cisco", SecureRandom.hex)
    cookies[:data] = @response.to_json
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CWhatsapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#dashboard</h1>
  <p>Find me in app/views/pages/dashboard.html.erb</p>
</div>

app/views/pages/index.html.erb
<div class="w-full flex flex-col">
  <div class="w-full flex justify-center">
    <%= link_to 'Welcome', send_welcome_path, class: 'text-purple-700 hover:text-white border border-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-purple-400 dark:text-purple-400 dark:hover:text-white dark:hover:bg-purple-500 dark:focus:ring-purple-900' %>

    <button type="button" class="text-purple-700 hover:text-white border border-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-purple-400 dark:text-purple-400 dark:hover:text-white dark:hover:bg-purple-500 dark:focus:ring-purple-900">1st recordatory</button>

    <button type="button" class="text-purple-700 hover:text-white border border-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-purple-400 dark:text-purple-400 dark:hover:text-white dark:hover:bg-purple-500 dark:focus:ring-purple-900">Regular</button>
  </div>

  <div class="w-full flex flex-col justify-center">
      <button type="button" class="text-purple-700 hover:text-white border border-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-purple-400 dark:text-purple-400 dark:hover:text-white dark:hover:bg-purple-500 dark:focus:ring-purple-900 overflow-hidden"><%= ENV['WHATSAPP_TOKEN'] %></button>
    <div class="border-2 border-red-500 hover:border-red-300 bg-red-100 hover:bg-red-50 opacity-70 text-red-600 px-10 py-7 rounded text-semibold text-lg">
      <%= JSON.pretty_generate(JSON.parse(cookies[:data])) %>
    </div>
  </div>
</div>